In [2]:
import numpy as np
import cv2 as cv
img = cv.imread('karoro.png')
assert img is not None, "file could not be read, check with os.path.exists()"
import warnings
warnings.filterwarnings('ignore')

In [3]:
dimension1,dimension2,dimension3=img.shape

In [4]:
img.shape

(171, 294, 3)

In [5]:
img.dtype

dtype('uint8')

In [6]:
img=img.astype(np.float64)

In [7]:
r=np.zeros((dimension1,dimension2),dtype=np.float64)
g=np.zeros((dimension1,dimension2),dtype=np.float64)
b=np.zeros((dimension1,dimension2),dtype=np.float64)

In [8]:
r.dtype


dtype('float64')

In [9]:
img.dtype


dtype('float64')

In [10]:
R=img[:,:,2]
G=img[:,:,1]
B=img[:,:,0]

In [11]:
r=img[:,:,2]/(img[:,:,0]+img[:,:,1]+img[:,:,2])
g=img[:,:,1]/(img[:,:,0]+img[:,:,1]+img[:,:,2])
b=img[:,:,0]/(img[:,:,0]+img[:,:,1]+img[:,:,2])

In [12]:
r.dtype

dtype('float64')

In [13]:
s=np.zeros((dimension1,dimension2),dtype=np.float64)

In [14]:
s.shape

(171, 294)

In [15]:
s.shape


(171, 294)

## S구하기

In [16]:
for i in range(dimension1):
    for j in range(dimension2):
        s[i][j]=(1-3*min([r[i][j],g[i][j],b[i][j]]))
    

In [17]:
s

array([[0.00787402, 0.00787402, 0.01051248, ..., 0.        , 0.        ,
        0.        ],
       [0.00787402, 0.00787402, 0.01051248, ..., 0.        , 0.        ,
        0.        ],
       [0.00787402, 0.00787402, 0.00787402, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [18]:
s=s*255

In [19]:
s

array([[2.00787402, 2.00787402, 2.68068331, ..., 0.        , 0.        ,
        0.        ],
       [2.00787402, 2.00787402, 2.68068331, ..., 0.        , 0.        ,
        0.        ],
       [2.00787402, 2.00787402, 2.00787402, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

## I 구하기

In [20]:
inten=np.zeros((dimension1,dimension2),dtype=np.float64)

In [21]:
for i in range(dimension1):
    for j in range(dimension2):
        inten[i][j]=(R[i][j]+G[i][j]+B[i][j])/(3)
    

In [22]:
inten

array([[254.        , 254.        , 253.66666667, ..., 255.        ,
        255.        , 255.        ],
       [254.        , 254.        , 253.66666667, ..., 255.        ,
        255.        , 255.        ],
       [254.        , 254.        , 254.        , ..., 255.        ,
        255.        , 255.        ],
       ...,
       [255.        , 255.        , 255.        , ..., 255.        ,
        255.        , 255.        ],
       [255.        , 255.        , 255.        , ..., 255.        ,
        255.        , 255.        ],
       [255.        , 255.        , 255.        , ..., 255.        ,
        255.        , 255.        ]])

## H구하기

In [23]:
h=np.zeros((dimension1,dimension2),dtype=np.uint8)

In [35]:
for i in range(dimension1):
    for j in range(dimension2):
        if R[i][j]<= B[i][j]:
            temp1=(0.5*(R[i][j]-G[i][j]+R[i][j]-B[i][j]))
            temp2=np.sqrt((R[i][j]-G[i][j])*(R[i][j]-G[i][j])+(R[i][j]-B[i][j])*(G[i][j]-B[i][j]))
            h[i][j]=144*np.arccos((temp1/temp2))
            
            #print(h[i][j])
        else:
            temp1=(0.5*(r[i][j]-g[i][j]+r[i][j]-b[i][j]))
            temp2=np.sqrt((r[i][j]-g[i][j])*(r[i][j]-g[i][j])+(r[i][j]-b[i][j])*(g[i][j]-b[i][j]))
            h[i][j]=144*(2*np.pi-np.arccos((temp1/temp2)))
            
    

In [36]:
h


array([[150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [37]:
#h=h.astype(np.uint8)

In [38]:
h

array([[150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [39]:
s=s.astype(np.uint8)
inten=inten.astype(np.uint8)
h=h.astype(np.uint8)

In [40]:
s

array([[2, 2, 2, ..., 0, 0, 0],
       [2, 2, 2, ..., 0, 0, 0],
       [2, 2, 2, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [41]:
inten

array([[254, 254, 253, ..., 255, 255, 255],
       [254, 254, 253, ..., 255, 255, 255],
       [254, 254, 254, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [42]:
h

array([[150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [43]:
count=0;
for i in range(dimension1):
    for j in range(dimension2):
        #if h[i][j]>0:
        #        count+=1
        print(h[i][j])

150
150
150
150
150
150
13
13
101
101
34
34
61
61
150
0
148
141
130
126
114
143
113
77
86
107
241
5
44
112
120
81
69
79
92
92
92
92
92
92
92
92
92
92
92
92
92
83
43
4
241
13
24
241
0
98
101
40
150
150
221
226
198
221
13
122
101
88
122
122
88
120
20
61
226
196
196
196
196
196
161
120
120
120
120
120
226
226
226
226
150
150
150
150
150
150
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
196
196
196
196
196
120
120
150
150
150
150
150
150
150
150
150
150
34
183
214
241
241
241
34
34
101
101
13
13
13
150
150
150
18
93
0
0
241
214
8
241
241
241
241
241
241
241
241
241
20
101
101
101
136
136
88
88
61
61
150
150
226
226
198
226
150
61
61
61
61
61
61
61
61
61
61
61
61
61
61
61
150
150
150
150
150
150
150
150
150
150
150
150
150
150
150
0
45
120
196
196
196
196
161
161
196
161
93
120
120
93
93
120
196
120
196
196
93
93
93
120
93
93
93
93
93
93
93
196
0
0
45
45
45
45
45
45
45
45
0
0
45
45
45
120
148
148
161
0
61
34
26
20
20
26
34
34
0
196
196
196
196
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
150
150
150
150
150
1

In [44]:
count

0

In [ ]:
cv.imshow('h',h)
cv.imshow('s',s)
cv.imshow('i',inten)
k = cv.waitKey(0)

cv.destroyAllWindows()