In [61]:
import numpy as np
import cv2 as cv
# Create a black image
img = np.zeros((512,512,3), np.uint8)
# Draw a diagonal blue line with thickness of 5 px
cv.line(img,(0,0),(511,511),(20,213,1),5)
cv.rectangle(img,(384,0),(510,128),(0,255,0),3)
cv.circle(img,(447,63), 63, (0,0,255), -1)
cv.ellipse(img,(256,256),(100,50),0,0,200,360,-1)

array([[[ 20, 213,   1],
        [ 20, 213,   1],
        [ 20, 213,   1],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[ 20, 213,   1],
        [ 20, 213,   1],
        [ 20, 213,   1],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[ 20, 213,   1],
        [ 20, 213,   1],
        [ 20, 213,   1],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 20, 213,   1],
        [ 20, 213,   1],
        [ 20, 213,   1]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 20, 213,   1],
        [ 20, 213,   1],
        [ 20, 213,   1]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 20, 213,   1],
        [ 20, 213,   1],
        [ 20, 213,   1]]

In [1]:
import numpy as np
import cv2 as cv
img = cv.imread('karoro.png')
assert img is not None, "file could not be read, check with os.path.exists()"

In [2]:
px=img[100,100]

In [3]:
print(px)

[226 239 247]


In [4]:
print(img.size)

150822


In [5]:
img1 = np.zeros((171,294,3), np.uint8)
img1.shape

(171, 294, 3)

In [6]:
height, width, channel = img.shape

In [7]:
b=img[:,:,0]

In [8]:
b

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [9]:

bgr = img.astype(np.float64) / 255.0

In [30]:
img

array([[[255, 252, 255],
        [255, 252, 255],
        [255, 251, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 252, 255],
        [255, 252, 255],
        [255, 251, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 252, 255],
        [255, 252, 255],
        [255, 252, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [10]:

b, g, r = cv.split(bgr)

In [11]:

h = np.zeros((height, width), dtype=np.float64)
s = np.zeros((height, width), dtype=np.float64)

In [29]:

v = np.max(bgr, axis=2)
v

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
for i in range(height):
    for j in range(width):
        if v[i][j] == 0:
            h[i][j] = 0
            s[i][j] = 0
        else:
            min_rgb = min(bgr[i][j])
            
            s[i][j] = 1 - (min_rgb / v[i][j])
            
            if v[i][j] == r[i][j]:
                h[i][j] = 60 * (g[i][j] - b[i][j]) / (v[i][j] - min_rgb)
            elif v[i][j] == g[i][j]:
                h[i][j] = 120 + (60 * (b[i][j] - r[i][j])) / (v[i][j] - min_rgb)
            elif v[i][j] == b[i][j]:
                h[i][j] = 240 + (60 * (r[i][j] - g[i][j])) / (v[i][j] - min_rgb)
            if h[i][j] < 0:
                h[i][j] += 360
            h[i][j] /= 360

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [20]:
hsv_img = (np.dstack((h, s, v)) * 255).astype(np.uint8)

In [27]:
cv.imshow('asdf',v)
k = cv.waitKey(0)

In [17]:
hsv_img

array([[[212,   2, 255],
        [212,   2, 255],
        [212,   4, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[212,   2, 255],
        [212,   2, 255],
        [212,   4, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[212,   2, 255],
        [212,   2, 255],
        [212,   2, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]