In [8]:
import numpy as np
import cv2 as cv
img = cv.imread('karoro.png')
assert img is not None, "file could not be read, check with os.path.exists()"
import warnings
warnings.filterwarnings('ignore')

In [9]:
print(np.pi)

3.141592653589793


In [10]:
print(img.size)

150822


In [11]:
img.shape

(171, 294, 3)

In [27]:
img1 = np.zeros(img.shape, np.uint8)
img1.shape

(171, 294, 3)

In [28]:
height, width, channel = img.shape

In [29]:

bgr = img.astype(np.float64)

In [30]:

b, g, r = cv.split(bgr)

In [52]:
hsv=cv.cvtColor(img,cv.COLOR_BGR2HSV)
h, s, v = cv.split(hsv)

cv.imshow("h", h)
cv.imshow("s", s)
cv.imshow("v", v)
cv.waitKey()
cv.destroyAllWindows()

In [51]:
h

array([[150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       [150, 150, 150, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

### 수평선

In [20]:
v=1-(3*np.max(bgr,axis=2))

In [21]:
v


array([[-2., -2., -2., ..., -2., -2., -2.],
       [-2., -2., -2., ..., -2., -2., -2.],
       [-2., -2., -2., ..., -2., -2., -2.],
       ...,
       [-2., -2., -2., ..., -2., -2., -2.],
       [-2., -2., -2., ..., -2., -2., -2.],
       [-2., -2., -2., ..., -2., -2., -2.]])

In [19]:

v = np.max(bgr, axis=2)
v

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [17]:
for i in range(height):
    for j in range(width):
        if v[i][j] == 0:
            h[i][j] = 0
            s[i][j] = 0
        else:
            min_rgb = min(bgr[i][j])
            
            s[i][j] = 1 - (min_rgb / v[i][j])
            
            if v[i][j] == r[i][j]:
                h[i][j] = 60 * (g[i][j] - b[i][j]) / (v[i][j] - min_rgb)
            elif v[i][j] == g[i][j]:
                h[i][j] = 120 + (60 * (b[i][j] - r[i][j])) / (v[i][j] - min_rgb)
            elif v[i][j] == b[i][j]:
                h[i][j] = 240 + (60 * (r[i][j] - g[i][j])) / (v[i][j] - min_rgb)
            if h[i][j] < 0:
                h[i][j] += 360
            h[i][j] /= 360

In [18]:
hsv_img = (np.dstack((h, s, v)) * 255).astype(np.uint8)

In [19]:
cv.imshow('asdf',hsv_img)
k = cv.waitKey(0)

In [17]:
hsv_img

array([[[212,   2, 255],
        [212,   2, 255],
        [212,   4, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[212,   2, 255],
        [212,   2, 255],
        [212,   4, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[212,   2, 255],
        [212,   2, 255],
        [212,   2, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]